extra-deps:
- dbus-0.10.10
- fdo-notify-0.3.1
- modular-arithmetic-1.2.1.1
# following three were suggested by stack
- tuple-0.3.0.2
- OneTuple-0.2.1
- libxml-sax-0.7.5
resolver: nightly-2015-07-01
flags: {}
packages:
- '.'
